# https://alacritty.org/config-alacritty.html
import = ["~/.config/alacritty/monokai-charcoal.toml"]
live_config_reload = true


[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"

[font]
normal = { family = "Berkeley Mono", style = "Regular" }
size = 13.25

# [keyboard]
# bindings = [
# { key = "p", mods = "Alt", action = "None" }
# ]


