

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"

[font]
normal = { family = "Berkeley Mono", style = "Regular" }
size = 13.25

[general]
live_config_reload = true
# https://alacritty.org/config-alacritty.html
import = ["~/.config/alacritty/tokyo-night.toml"]

# [keyboard]
# bindings = [
# { key = "p", mods = "Alt", action = "None" }
# ]


